server:
  port: 8088

debug: true

spring:
  jpa:
    hibernate:
      ddlAuto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/herdsofbuffalos
    username: buffalo
    password: buffalo