server:
  port: 8089

logging:
  level:
    root: INFO
    com:
      buffalosoftware:
        processengine:
          recruitment:
            delegate:
              RecruitUnitTask: DEBUG

spring:
  jpa:
    hibernate:
      ddlAuto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/herdsofbuffalos
    username: buffalo
    password: buffalo
camunda.bpm:
  admin-user:
    id: buffalo
    password: buffalo
    firstName: Buffalo
  filter:
    create: All tasks
  job-execution:
    max-wait: 1000