server:
  port: 8088

debug: true

spring:
  jpa:
    hibernate:
      ddlAuto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/herds-of-buffalos
    username: buffalo
    password: buffalo
  h2:
    console:
      enabled: true
      path: /db